services:
  mysql:
    container_name: mysql_container
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-yourdatabase}
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    volumes:
      - ./php-make/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - mysql
    ports:
      - "6060:80"
    networks:
      - mysql
    restart: unless-stopped

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  mysql: